project_id = "jneacqixiglkfkvtwxwe"

[functions.create-checkout]
verify_jwt = false

[functions.create-boost-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false